# Generated by Django 5.2.16 on 2026-07-09 11:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


ROLE_NAMES = ["member", "buddy", "leader"]


def create_role_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for name in ROLE_NAMES:
        Group.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_role_groups, migrations.RunPython.noop),
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(default=django.utils.timezone.localdate)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buddy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentorships_as_buddy', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentorships_as_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('member',), name='unique_active_member_mentorship'), models.CheckConstraint(condition=models.Q(('member', models.F('buddy')), _negated=True), name='mentorship_member_not_buddy'), models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='mentorship_end_after_start')],
            },
        ),
    ]
