services:
  nginx:
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - staticfiles:/app/staticfiles:ro
      - media:/app/media:ro
      - ./docker/nginx.https.conf:/etc/nginx/conf.d/default.conf:ro
      - /opt/team_learn_plan_ssl:/etc/nginx/ssl:ro
