# Generated by Django 5.2.16 on 2026-07-09 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapabilityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'capability category',
                'verbose_name_plural': 'capability categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('material_type', models.CharField(blank=True, max_length=100)),
                ('source', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CapabilityDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')])),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='learning.capabilitycategory')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='learning.capabilitydomain')),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CapabilityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('suggested_level', models.CharField(blank=True, max_length=50)),
                ('material_reference', models.TextField(blank=True)),
                ('acceptance_method', models.TextField(blank=True)),
                ('estimated_hours', models.CharField(blank=True, max_length=50)),
                ('recommended_action', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='learning.capabilitydomain')),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CapabilityMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_materials', to='learning.capabilityitem')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capability_materials', to='learning.learningmaterial')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='capabilityitem',
            name='materials',
            field=models.ManyToManyField(related_name='capability_items', through='learning.CapabilityMaterial', to='learning.learningmaterial'),
        ),
        migrations.AddConstraint(
            model_name='capabilitydomain',
            constraint=models.CheckConstraint(condition=models.Q(('level__in', [1, 2])), name='learning_domain_level_valid'),
        ),
        migrations.AddConstraint(
            model_name='capabilitydomain',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('level', 1), ('parent__isnull', True)), models.Q(('level', 2), ('parent__isnull', False)), _connector='OR'), name='learning_domain_level_parent_consistent'),
        ),
        migrations.AddConstraint(
            model_name='capabilitymaterial',
            constraint=models.UniqueConstraint(fields=('item', 'material'), name='learning_item_material_unique'),
        ),
    ]
