# Generated by Django 5.2.16 on 2026-07-09 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('cycle_type', models.CharField(choices=[('calendar_year', '自然年'), ('rolling_12_month', '连续 12 个月')], max_length=20)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', '进行中'), ('archived', '已归档')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CycleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_participations', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='learning.learningcycle')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gap', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('', '未设置'), ('high', '高'), ('medium', '中'), ('low', '低')], max_length=10)),
                ('included', models.BooleanField(default=False)),
                ('planned_quarter', models.CharField(blank=True, choices=[('', '未设置'), ('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=3)),
                ('planned_month', models.DateField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='learning.capabilityitem')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='learning.learningcycle')),
            ],
        ),
        migrations.AddConstraint(
            model_name='learningcycle',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='learning_cycle_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='learningcycle',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cycle_type', 'calendar_year'), ('year__isnull', False)), models.Q(('cycle_type', 'rolling_12_month'), ('year__isnull', True)), _connector='OR'), name='learning_cycle_year_consistent'),
        ),
        migrations.AddConstraint(
            model_name='cycleparticipant',
            constraint=models.UniqueConstraint(fields=('cycle', 'member'), name='learning_cycle_participant_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('member', 'cycle', 'capability_item'), name='learning_assessment_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('current_level__isnull', True), models.Q(('current_level__gte', 0), ('current_level__lte', 5)), _connector='OR'), name='learning_assessment_current_level_range'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('target_level__isnull', True), models.Q(('target_level__gte', 0), ('target_level__lte', 5)), _connector='OR'), name='learning_assessment_target_level_range'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('gap__isnull', True), ('gap__gte', 0), _connector='OR'), name='learning_assessment_gap_nonnegative'),
        ),
    ]
