# Generated by Django 5.2.16 on 2026-07-10 01:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_learningcycle_cycleparticipant_assessment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_approval', '待 Buddy 审批'), ('changes_requested', '需修改'), ('active', '执行中')], default='draft', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buddy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buddy_learning_plans', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_plans', to='learning.learningcycle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanApprovalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', '已提交'), ('changes_requested', '退回修改'), ('approved', '已批准')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_approval_events', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_events', to='learning.learningplan')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability_code', models.CharField(max_length=20)),
                ('capability_name', models.CharField(max_length=200)),
                ('suggested_level', models.CharField(blank=True, max_length=50)),
                ('materials_snapshot', models.TextField(blank=True)),
                ('current_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gap', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('', '未设置'), ('high', '高'), ('medium', '中'), ('low', '低')], max_length=10)),
                ('planned_quarter', models.CharField(blank=True, choices=[('', '未设置'), ('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=3)),
                ('planned_month', models.DateField(blank=True, null=True)),
                ('task', models.TextField(blank=True)),
                ('acceptance_method', models.TextField(blank=True)),
                ('estimated_hours', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='learning.assessment')),
                ('capability_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='learning.capabilityitem')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learning.learningplan')),
            ],
            options={
                'ordering': ['sort_order', 'capability_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='learningplan',
            constraint=models.UniqueConstraint(fields=('member', 'cycle'), name='learning_plan_member_cycle_unique'),
        ),
        migrations.AddConstraint(
            model_name='planitem',
            constraint=models.UniqueConstraint(fields=('plan', 'assessment'), name='learning_plan_item_assessment_unique'),
        ),
    ]
