# Generated by Django 5.2.16 on 2026-07-10 02:05

import apps.learning.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_learningplan_planapprovalevent_planitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planitem',
            name='execution_status',
            field=models.CharField(choices=[('working', '执行中'), ('pending_review', '待验收'), ('changes_requested', '需补充'), ('completed', '已完成')], default='working', max_length=30),
        ),
        migrations.CreateModel(
            name='EvidenceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('batch_no', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_submissions', to='learning.planitem')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.learning.models.evidence_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='learning.evidencesubmission')),
            ],
            options={
                'ordering': ['uploaded_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='GuidanceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guidance_comments', to=settings.AUTH_USER_MODEL)),
                ('plan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidance_comments', to='learning.planitem')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('hours_spent', models.DecimalField(decimal_places=1, max_digits=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_updates', to=settings.AUTH_USER_MODEL)),
                ('plan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='learning.planitem')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('changes_requested', '退回修改'), ('completed', '验收通过')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_decisions', to='learning.evidencesubmission')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
