# Generated by Django 5.2.16 on 2026-07-10 02:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_planitem_execution_status_evidencesubmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_names', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('capability_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_logs', to='learning.capabilityitem')),
                ('plan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_sync_logs', to='learning.planitem')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
